### Listar profissionais
GET http://localhost:3007/profissionais
Accept: application/json

### Criar paciente
POST http://localhost:3007/pacientes
Content-Type: application/json

{
  "nomeCompleto": "João da Silva",
  "email": "joao5@email.com",
  "cpf": "123.456.789-66",
  "celular": "98999999999",
  "idade": 25,
  "cidade": "São Luís",
  "estado": "MA"
}

### Criar atendimento
POST http://localhost:3007/atendimentos
Content-Type: application/json

{
  "descricao": "Consulta inicial",
  "horario_atendimento": "2026-02-01T14:00:00.000Z",
  "therapistId": 1,
  "patientId": 1,
  "tipo_atendimento": "SOCIAL"
}

### listar atendimento pendentes
GET http://localhost:3007/atendimentos/pendentes
Content-Type: application/json

### admin solitacoes
GET http://localhost:3007/admin/solicitacoes
Content-Type: application/json

### admin atendimentos
GET http://localhost:3007/admin/atendimentos  
Content-Type: application/json

### admin profissionais
GET http://localhost:3007/admin/profissionais  
Content-Type: application/json

### admin pacientes
GET http://localhost:3007/admin/pacientes  
Content-Type: application/json

### dashboard paciente
GET http://localhost:3007/dashboard/paciente/1 
Content-Type: application/json

### dashboard PROFISSIONAL
GET http://localhost:3007/dashboard/profissional/1 
Content-Type: application/json

### atualizar PROFISSIONAL
PUT http://localhost:3007/profissional/1 
Content-Type: application/json

{
  "nomeCompleto": "Maria Oliveira",
  "celular": "98988887776",
  "horarioDisponivel": "Seg–Sex 08:00–18:00",
  "tipo_atendimento": "SOCIAL",
  "abordagem_e_experiencia": "TCC, 5 anos de experiência",
  "numero_registro": "CRP 06/12345",
  "pix": "maria@pix.com",
  "cpf": "123.456.789-05"
}

### atualizar PACIENTE
PUT http://localhost:3007/paciente/1 
Content-Type: application/json

{
  "nomeCompleto": "João da Silva",
  "cpf": "123.456.789-68",
  "celular": "98999999999",
  "idade": 25,
  "cidade": "São Luís",
  "estado": "MA"
}

### Criar terapeuta
POST http://localhost:3007/profissionais
Content-Type: application/json

{
  "nomeCompleto": "Dra. Ana Lima",
  "email": "ana55@email.com",
  "celular": "5598999999999",
  "horarioDisponivel": "Seg-Sex 18:00-21:00",
  "numero_registro": "CRP 00/00000",
  "abordagem_e_experiencia": "TCC, 5 anos de experiência...",
  "pix": "chave-pix@email.com",
  "cpf": "123.456.789-33"
}

### Criar terapeuta
POST http://localhost:3007/pay
Content-Type: application/json

{
  "metodo": "pix",
  "nome": "João Silva",
  "email": "joao@email.com",
  "telefone": "5598999999999",
  "cpf": "61629859389"
}

### LOGIN
POST http://localhost:3007/auth/login
Content-Type: application/json

{
  "email": "maria.oliveira3@email.com",
  "cpf": "123.456.789-02",
  "tipo": "THERAPIST"
}